# Lab03v100Young.py
# The First Program
# This is the Student Starting version of Lab03.
#
print("REQUIRED FOR 80 & 100 POINT VERSIONS")   
print("()")
print("*******************************")
print("Lab 03A, THE FIRST PROGRAM")
print("80 POINT VERSION")
print("BY COOPER YOUNG")
print("*******************************")
print("()")
print("A poet I am not")
print("Don't claim to be")
print("But what I wrote")
print("Did come from me")
print ("")
print ("")
print("REQUIRED FOR 100 POINT VERSIONS") 
print (3 + 10)
print (8 - 1)
print (3 * 10)
print (10 / 3)
print (10 // 3)
print (10 % 3)
print (10 ** 3)
